apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-edge-2
  namespace: default
  labels:
    app: ai-edge-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-edge-2
  template:
    metadata:
      labels:
        app: ai-edge-2
    spec:
      containers:
      - name: ai-edge-2
        image: gcav66/keras-app
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: ai-edge-2
  namespace: default
spec:
  selector:
    app: ai-edge-2
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30102
